const categories = [
  {
    id: "homemade-fatayer",
    label: "Homemade Fatayer",
    headerData: {
      image: "",
      title: "Homemade Fatayer",
      hint: "All prices are inclusive of 10% VAT",
    },
    items: [
      {
        id: 1,
        name: "Spinach & Pinenuts Fatayer",
        price: "BD0.700",
        desc: "Wholemeal flour fatayer, spinach & pine nuts filling.",
      },
      {
        id: 2,
        name: "Za'atar Fatayer",
        price: "BD0.300",
        desc: "Wholemeal flour fatayer & homemade Za'atar mix.",
      },
      {
        id: 3,
        name: "Cheese Fatayer",
        price: "BD0.600",
        desc: "Fatayer filled with melted cheese.",
      },
      {
        id: 4,
        name: "Meat Fatayer",
        price: "BD0.800",
        desc: "Fatayer with seasoned minced meat.",
      },
      {
        id: 5,
        name: "Vegetable Fatayer",
        price: "BD0.500",
        desc: "Fatayer with mixed vegetable filling.",
      },
      {
        id: 6,
        name: "Chicken Fatayer",
        price: "BD0.900",
        desc: "Fatayer stuffed with spiced chicken.",
      },
      {
        id: 7,
        name: "Sweet Fatayer",
        price: "BD0.400",
        desc: "Fatayer with a sweet date filling.",
      },
    ],
  },
  {
    id: "viennoiseries",
    label: "Viennoiseries & Pastries",
    headerData: {
      image: "",
      title: "Viennoiseries & Pastries",
      hint: "Perfect for breakfast or tea time!",
    },
    items: [
      {
        id: 8,
        name: "Croissant",
        price: "BD0.500",
        desc: "Flaky butter croissant.",
      },
      {
        id: 9,
        name: "Pain au Chocolat",
        price: "BD0.600",
        desc: "Croissant with chocolate filling.",
      },
      {
        id: 10,
        name: "Almond Croissant",
        price: "BD0.700",
        desc: "Croissant topped with almonds and powdered sugar.",
      },
      {
        id: 11,
        name: "Cinnamon Roll",
        price: "BD0.800",
        desc: "Sweet pastry rolled with cinnamon and sugar.",
      },
      {
        id: 12,
        name: "Danish Pastry",
        price: "BD0.750",
        desc: "Danish pastry with custard and fruit topping.",
      },
      {
        id: 13,
        name: "Butter Brioche",
        price: "BD1.000",
        desc: "Soft, buttery brioche bread.",
      },
      {
        id: 14,
        name: "Apple Turnover",
        price: "BD0.900",
        desc: "Pastry filled with sweet apple filling.",
      },
    ],
  },
  {
    id: "pasta",
    label: "Pasta",
    headerData: {
      image: "",
      title: "Pasta",
      hint: "A selection of delicious Italian-inspired dishes.",
    },
    items: [
      {
        id: 15,
        name: "Spaghetti Bolognese",
        price: "BD1.800",
        desc: "Classic pasta with meat sauce.",
      },
      {
        id: 16,
        name: "Penne Alfredo",
        price: "BD1.600",
        desc: "Pasta in creamy Alfredo sauce.",
      },
      {
        id: 17,
        name: "Seafood Linguine",
        price: "BD2.500",
        desc: "Pasta with mixed seafood.",
      },
      {
        id: 18,
        name: "Lasagna",
        price: "BD2.200",
        desc: "Layered pasta with meat and cheese.",
      },
      {
        id: 19,
        name: "Pesto Pasta",
        price: "BD1.800",
        desc: "Pasta with basil pesto sauce.",
      },
      {
        id: 20,
        name: "Mac and Cheese",
        price: "BD1.500",
        desc: "Cheesy macaroni pasta.",
      },
      {
        id: 21,
        name: "Ravioli",
        price: "BD2.000",
        desc: "Pasta stuffed with spinach and ricotta cheese.",
      },
    ],
  },
  {
    id: "snacks",
    label: "Snacks",
    headerData: {
      image: "",
      title: "Snacks",
      hint: "Perfect for a quick bite!",
    },
    items: [
      {
        id: 22,
        name: "French Fries",
        price: "BD0.800",
        desc: "Crispy golden fries.",
      },
      {
        id: 23,
        name: "Nachos",
        price: "BD1.500",
        desc: "Nachos with cheese and toppings.",
      },
      {
        id: 24,
        name: "Chicken Wings",
        price: "BD2.000",
        desc: "Spicy grilled chicken wings.",
      },
      {
        id: 25,
        name: "Mozzarella Sticks",
        price: "BD1.800",
        desc: "Cheese-filled sticks.",
      },
      {
        id: 26,
        name: "Spring Rolls",
        price: "BD0.900",
        desc: "Crispy spring rolls with vegetable filling.",
      },
      {
        id: 27,
        name: "Mini Burgers",
        price: "BD2.500",
        desc: "Bite-sized beef burgers.",
      },
      {
        id: 28,
        name: "Onion Rings",
        price: "BD1.000",
        desc: "Crunchy onion rings.",
      },
    ],
  },
  {
    id: "seafood",
    label: "Seafood",
    headerData: {
      image: "",
      title: "Seafood",
      hint: "Fresh from the ocean to your plate.",
    },
    items: [
      {
        id: 29,
        name: "Grilled Salmon",
        price: "BD4.000",
        desc: "Freshly grilled salmon fillet.",
      },
      {
        id: 30,
        name: "Fish and Chips",
        price: "BD2.500",
        desc: "Fried fish with crispy fries.",
      },
      {
        id: 31,
        name: "Prawns Curry",
        price: "BD3.200",
        desc: "Prawns cooked in rich curry.",
      },
      {
        id: 32,
        name: "Crab Cakes",
        price: "BD3.500",
        desc: "Golden crab cakes with sauce.",
      },
      {
        id: 33,
        name: "Lobster Thermidor",
        price: "BD8.000",
        desc: "Baked lobster with creamy sauce.",
      },
      {
        id: 34,
        name: "Fried Calamari",
        price: "BD2.800",
        desc: "Crispy fried calamari rings.",
      },
      {
        id: 35,
        name: "Seafood Platter",
        price: "BD6.000",
        desc: "Assortment of grilled seafood.",
      },
    ],
  },
  {
    id: "burgers",
    label: "Burgers",
    headerData: {
      image: "",
      title: "Burgers",
      hint: "Juicy and delicious burgers made fresh to order.",
    },
    items: [
      {
        id: 36,
        name: "Classic Beef Burger",
        price: "BD2.500",
        desc: "Beef patty with lettuce, tomato, and cheese.",
      },
      {
        id: 37,
        name: "Cheeseburger",
        price: "BD2.800",
        desc: "Classic burger with extra cheese.",
      },
      {
        id: 38,
        name: "Chicken Burger",
        price: "BD2.300",
        desc: "Grilled chicken with a tangy sauce.",
      },
      {
        id: 39,
        name: "Veggie Burger",
        price: "BD2.000",
        desc: "Patty made from fresh vegetables.",
      },
      {
        id: 40,
        name: "Double Cheeseburger",
        price: "BD3.200",
        desc: "Two beef patties with melted cheese.",
      },
      {
        id: 41,
        name: "Bacon Cheeseburger",
        price: "BD3.500",
        desc: "Burger topped with crispy bacon and cheese.",
      },
      {
        id: 42,
        name: "Spicy Chicken Burger",
        price: "BD2.600",
        desc: "Spicy chicken fillet with jalapeños.",
      },
    ],
  },
  {
    id: "desserts",
    label: "Desserts",
    headerData: {
      image: "",
      title: "Desserts",
      hint: "Indulge in our sweet and delightful treats.",
    },
    items: [
      {
        id: 43,
        name: "Chocolate Cake",
        price: "BD1.200",
        desc: "Rich chocolate cake with creamy frosting.",
      },
      {
        id: 44,
        name: "Baklava",
        price: "BD0.900",
        desc: "Layers of filo pastry with nuts and syrup.",
      },
      {
        id: 45,
        name: "Cheesecake",
        price: "BD1.500",
        desc: "Creamy cheesecake with a biscuit base.",
      },
      {
        id: 46,
        name: "Brownie",
        price: "BD1.000",
        desc: "Fudgy chocolate brownie.",
      },
      {
        id: 47,
        name: "Tiramisu",
        price: "BD1.800",
        desc: "Italian dessert with coffee-soaked layers.",
      },
      {
        id: 48,
        name: "Apple Pie",
        price: "BD1.300",
        desc: "Classic apple pie with a flaky crust.",
      },
      {
        id: 49,
        name: "Ice Cream Sundae",
        price: "BD1.500",
        desc: "Ice cream topped with syrup and nuts.",
      },
    ],
  },
  {
    id: "drinks",
    label: "Drinks",
    headerData: {
      image: "",
      title: "Drinks",
      hint: "Stay refreshed with our selection of beverages.",
    },
    items: [
      {
        id: 50,
        name: "Iced Coffee",
        price: "BD1.200",
        desc: "Chilled coffee with ice and milk.",
      },
      {
        id: 51,
        name: "Fresh Orange Juice",
        price: "BD1.500",
        desc: "Freshly squeezed orange juice.",
      },
      {
        id: 52,
        name: "Smoothie",
        price: "BD1.800",
        desc: "Blended fruit smoothie.",
      },
      {
        id: 53,
        name: "Milkshake",
        price: "BD1.500",
        desc: "Milkshake with your choice of flavor.",
      },
      {
        id: 54,
        name: "Lemon Mint",
        price: "BD1.000",
        desc: "Refreshing lemon and mint drink.",
      },
      {
        id: 55,
        name: "Hot Chocolate",
        price: "BD1.000",
        desc: "Rich and creamy hot chocolate.",
      },
      {
        id: 56,
        name: "Tea",
        price: "BD0.800",
        desc: "Your choice of black or green tea.",
      },
      {
        id: 57,
        name: "Espresso",
        price: "BD0.900",
        desc: "Strong and bold espresso shot.",
      },
    ],
  },
  {
    id: "grills",
    label: "Grills",
    headerData: {
      image: "",
      title: "Grills",
      hint: "Perfectly grilled dishes, full of flavor.",
    },
    items: [
      {
        id: 58,
        name: "Chicken Kebab",
        price: "BD2.000",
        desc: "Grilled chicken skewers.",
      },
      {
        id: 59,
        name: "Beef Steak",
        price: "BD3.500",
        desc: "Juicy beef steak.",
      },
      {
        id: 60,
        name: "Lamb Chops",
        price: "BD4.000",
        desc: "Tender lamb chops grilled to perfection.",
      },
      {
        id: 61,
        name: "Mixed Grill Platter",
        price: "BD5.000",
        desc: "A variety of grilled meats.",
      },
      {
        id: 62,
        name: "Shish Tawook",
        price: "BD2.500",
        desc: "Marinated chicken grilled on skewers.",
      },
      {
        id: 63,
        name: "Grilled Prawns",
        price: "BD3.800",
        desc: "Charcoal-grilled prawns.",
      },
      {
        id: 64,
        name: "Grilled Vegetables",
        price: "BD1.500",
        desc: "Assorted grilled vegetables.",
      },
    ],
  },
  {
    id: "salads",
    label: "Salads",
    headerData: {
      image: "",
      title: "Salads",
      hint: "Healthy and refreshing salad options.",
    },
    items: [
      {
        id: 65,
        name: "Caesar Salad",
        price: "BD1.000",
        desc: "Romaine lettuce with Caesar dressing and croutons.",
      },
      {
        id: 66,
        name: "Greek Salad",
        price: "BD0.800",
        desc: "Fresh vegetables with feta cheese and olives.",
      },
      {
        id: 67,
        name: "Quinoa Salad",
        price: "BD1.200",
        desc: "Quinoa with fresh veggies and lemon dressing.",
      },
      {
        id: 68,
        name: "Chicken Salad",
        price: "BD1.500",
        desc: "Grilled chicken with a mix of greens.",
      },
      {
        id: 69,
        name: "Tuna Salad",
        price: "BD1.400",
        desc: "Tuna mixed with fresh greens and dressing.",
      },
      {
        id: 70,
        name: "Caprese Salad",
        price: "BD1.300",
        desc: "Tomatoes, mozzarella, and basil drizzled with olive oil.",
      },
      {
        id: 71,
        name: "Fruit Salad",
        price: "BD1.000",
        desc: "Fresh seasonal fruits.",
      },
    ],
  },
];

export default categories;
